// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIQhTk4XZerGGu4laoVpywvmCkIt2rqVM',
    appId: '1:501291905076:web:b3393a22cfe09a3e521a61',
    messagingSenderId: '501291905076',
    projectId: 'crm-sapinf',
    authDomain: 'crm-sapinf.firebaseapp.com',
    storageBucket: 'crm-sapinf.firebasestorage.app',
    measurementId: 'G-V91D3QSHDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPE6fIoCGvqMof_dvssrhNL6qZVp3vtIs',
    appId: '1:501291905076:android:53c73943986004cb521a61',
    messagingSenderId: '501291905076',
    projectId: 'crm-sapinf',
    storageBucket: 'crm-sapinf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnSRJuMz5xPEzlifLqdw99-sVb_EEMXx8',
    appId: '1:501291905076:ios:eb6cb9ea5fd643f5521a61',
    messagingSenderId: '501291905076',
    projectId: 'crm-sapinf',
    storageBucket: 'crm-sapinf.firebasestorage.app',
    iosBundleId: 'com.example.crmSapinf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnSRJuMz5xPEzlifLqdw99-sVb_EEMXx8',
    appId: '1:501291905076:ios:eb6cb9ea5fd643f5521a61',
    messagingSenderId: '501291905076',
    projectId: 'crm-sapinf',
    storageBucket: 'crm-sapinf.firebasestorage.app',
    iosBundleId: 'com.example.crmSapinf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIQhTk4XZerGGu4laoVpywvmCkIt2rqVM',
    appId: '1:501291905076:web:cfa8cfead093fbda521a61',
    messagingSenderId: '501291905076',
    projectId: 'crm-sapinf',
    authDomain: 'crm-sapinf.firebaseapp.com',
    storageBucket: 'crm-sapinf.firebasestorage.app',
    measurementId: 'G-Z6WTJZYG9L',
  );
}
